#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/pzog
  
  rm -rf build/* 
  
  pySloc -L py psprog pzogd ringDataGen  -X dist -X limbo -v $@
else
  echo "DEV_BASE is not defined"
fi
