#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/pzog
  
  autopep8 -ai -r pzog ring_data_gen psprog pzogd *.py
  echo "not styling logs/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
