#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/pzog
  
  autopep8 -air src tests
  autopep8 -ai  src/psprog src/pzogd src/ring_data_gen
  echo "not styling logs/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
