[meta]
version = "0.1.0"

[project]
name = "pzog"
package = "pzog"
main_lang = "py"
version = "0.6.11"
version_date = "2017-12-13"
author = "Jim Dixon"
author_email = "jdd@gmail.com"
copyright = "2012-2017"
description = "organize ring of 5-6 machines sharing data over full mesh"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/pzog"
state = "shared"
url = "https://jddixon.github.io/pzog"

[python]
packages = [ "pzog",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = [ "src/psprog", "src/pzogd", "src/ring_data_gen",]
ext_modules = []
distshare = [ "optionz", "rnglib", "xlattice_py']]     requirements = ['setuptools']     test_requirements = ['pycrypt",]
